feat: 별점 등록 기능 구현
Shimpyo-House/Shimpyo_BE pull request #21
Opened 2023-11-25 17:16 UTC by jo0oy

### 💡 Motivation
- 별점 등록 기능을 개발합니다.
- Test 환경 Redis를 위해 Testcontainers Redis를 설정합니다.

### 📌 Changes
- 별점 등록 Request/Response DTO 추가
- 별점 등록 비즈니스 로직 구현, API 구현
- 별점 등록 기능 관련 Test Code 작성 후 동작 확인
- appliacaion.yml 'test' 프로파일에 `spring.jpa.show-sql=true` 설정 추가
- 별점 등록 기능 Rest Docs를 위한 Test 작성
- `build.gradle`에 testcontainers 의존성 추가
- test 용 redis container 설정 추가된 `AbstractContainersSupport` 추상 클래스 추가

### 🫱🏻‍🫲🏻 To Reviewers
- test 에서 redis를 사용해야할 경우 `AbstractContainersSupport`를 `extends`해서 사용하면 됩니다!

This close #12

2023-11-26 15:57 UTC, wocjf0513 approved these changes

2023-11-26 15:57 UTC, wocjf0513 commented on src/main/java/com/fc/shimpyo_be/domain/star/exception/EntityNotFoundException.java
global controll advice에서 applicationException을 catch하고 있기 때문에  RuntimeException을 extends하는 ApplicationException을 extends하는 방향으로 통일하면 좋을거같아요~ 💯

2023-11-26 15:57 UTC, wocjf0513 commented on src/test/java/com/fc/shimpyo_be/config/AbstractContainersSupport.java
감사합니다. 잘 사용하겠습니다 👍

2023-11-27 04:01 UTC, JeongUijeong requested changes
수고 많으셨습니다! 코드 너무 깔끔하고 좋네요~ ㅎㅎ 몇 가지 코멘트 달아 뒀으니, 확인해주시고, 수정 부탁드립니다! 🩷

2023-11-27 04:01 UTC, JeongUijeong commented on src/main/java/com/fc/shimpyo_be/domain/star/controller/StarRestController.java
> +    public ResponseEntity<?> register(@Valid @RequestBody StarRegisterRequestDto request) {
ResponseEntity<?> 처럼 제네릭을 쓰는 대신 ResponseEntity<ResponseDto<StarResponseDto>> 를 쓰면 더 명시적일 것 같아요~ㅎㅎ

2023-11-27 04:01 UTC, JeongUijeong commented on src/main/java/com/fc/shimpyo_be/domain/star/dto/request/StarRegisterRequestDto.java
> +    Long memberId,
회원 아이디는 요청 필드로 받는 것보다 SecurityUtil의 getCurrentMemberId 메서드를 이용하는 것은 어떤가요?

2023-11-27 04:01 UTC, JeongUijeong commented on src/test/java/com/fc/shimpyo_be/config/AbstractContainersSupport.java
감사합니다!!! 😁

2023-11-27 04:01 UTC, JeongUijeong commented on src/test/java/com/fc/shimpyo_be/domain/star/unit/service/StarServiceTest.java
> +@SpringBootTest
서비스 테스트는 단위 테스트로 진행해주시면 좋을 것 같아요! 컨트롤러 같은 경우는 Security 설정을 적용하기 위해 제한적으로 @SpringBootTest를 사용한 통합테스트를 진행하고 있습니다만, 서비스는 Security 설정이 필요없으니 단위테스트로 작성해주시면 감사하겠습니다 😊

2023-11-27 07:27 UTC, jo0oy commented on src/main/java/com/fc/shimpyo_be/domain/star/dto/request/StarRegisterRequestDto.java
> +    Long memberId,
넵넵 알겠습니다!

2023-11-27 07:32 UTC, jo0oy commented on src/test/java/com/fc/shimpyo_be/domain/star/unit/service/StarServiceTest.java
> +@SpringBootTest
옙 알겠습니다 :) ㅎㅎㅎ 앞으로 단위 테스트로 진행할게요!

2023-11-27 07:33 UTC, jo0oy commented on src/main/java/com/fc/shimpyo_be/domain/star/exception/EntityNotFoundException.java
넵 수정하겠습니다!

2023-11-27 11:13 UTC, jo0oy reviewed
여러분 코드리뷰 감사해용~🙂

2023-11-27 13:17 UTC, JeongUijeong approved these changes
수고하셨습니다 ㅎㅎ 최고!!

2023-11-27 13:17 UTC, merged