feat: 상품 전체 조회 및 상세 조회 기능 구현
Shimpyo-House/Shimpyo_BE pull request #8
Opened 2023-11-23 06:55 UTC by wocjf0513

💡 Motivation
숙박 예약을 하기 위해서는 어떤 숙소가 있고,
그 숙소에 어떤 방들이 있는지 알아야 합니다.

📌 Changes
상품 전체 조회 기능 구현
상품 상세 조회 기능 구현
예약 가능 방인지 확인 API 구현 중

🫱🏻‍🫲🏻 To Reviewers
각각의 기능들과 REST DOCS 적용해서 올립니다! 
현재, 예약가능 방인지 확인하기 기능이 구현 중에 있습니다.!
수정해야 될 부분있으면 자유롭게 review 주세요.

2023-11-23 07:56 UTC, jo0oy commented on src/main/java/com/fc/shimpyo_be/domain/product/controller/ProductController.java
의정님이 하신 것처럼 저희 다같이 -RestController로 통일하면 좋을 것 같습니다!

2023-11-23 08:00 UTC, jo0oy commented on src/main/java/com/fc/shimpyo_be/domain/product/entity/Category.java
enum 클래스에 직접적으로 한글 명칭을 넣는 것보다 기존처럼 영어로 enum 타입을 정의하고 'description' 같은 필드를 두고 그 필드에 한글 명칭 같은 설명을 넣어서 getter로 responseDto와 mapping 해주는 것이 좋을 것 같습니다!

2023-11-23 08:01 UTC, wocjf0513 commented on src/main/java/com/fc/shimpyo_be/domain/product/controller/ProductController.java
좋습니다.!

2023-11-23 08:01 UTC, wocjf0513 commented on src/main/java/com/fc/shimpyo_be/domain/product/entity/Category.java
감사합니다.

2023-11-23 08:19 UTC, jo0oy commented on src/main/java/com/fc/shimpyo_be/domain/room/entity/Room.java
> +    private Time checkIn;
저희 프로젝트 공통적으로 LocalDate/LocalDateTime을 사용하고 있기 때문에 checkIn, checkOut도 Entity에서 LocalTime 타입으로 정의하고 @Column(columnDefinition = "TIME") 으로 변경하는 것이 좋겠습니다!

2023-11-23 08:22 UTC, jo0oy requested changes
코드 리뷰 확인 후 수정 하실 수 있는 부분은 수정 부탁드립니다!

2023-11-23 08:25 UTC, wocjf0513 commented on src/main/java/com/fc/shimpyo_be/domain/room/entity/Room.java
> +    private Time checkIn;
네네 감사합니다!!

2023-11-23 15:50 UTC, JeongUijeong requested changes
수고 많으셨습니다! ㅎㅎ 코드 보면서 많이 배운 것 같습니당!
몇 가지 코멘트 남겼으니 확인 부탁드려요~
추가적으로, Service, Repository 단위 테스트 추가해주시면 좋을 것 같고, 응답은 ResponseEntity에 ResponseDto를 body로 넣어서 해주시면 너무 좋을 것 같습니다!

2023-11-23 15:50 UTC, JeongUijeong commented on src/main/java/com/fc/shimpyo_be/domain/product/controller/ProductRestController.java
> +    @GetMapping("")
("")은 생략하셔도 됩니다!

2023-11-23 15:50 UTC, JeongUijeong commented on src/main/java/com/fc/shimpyo_be/domain/product/controller/ProductRestController.java
> +    public ResponseDto<List<ProductResponse>> getAllProducts(
ResponseEntity body에 ResponseDto를 담으셔야 합니다! 지금처럼 하시면 응답 상태 코드가 제대로 안 담길 수 있습니다~
ex) ResponseEntity<ResponseDto<List<ProductResponse>>

2023-11-23 15:50 UTC, JeongUijeong commented on src/main/java/com/fc/shimpyo_be/domain/product/dto/response/ProductDetailsResponse.java
> +                                     String productName, String description, Boolean favorites, Float starAvg,
줄 띄움이 구글 컨벤션에 맞지 않는 것 같아요! 구글 컨벤션을 적용해주세요~

2023-11-23 15:50 UTC, JeongUijeong commented on src/main/java/com/fc/shimpyo_be/domain/product/dto/response/ProductResponse.java
> +public record ProductResponse(Long productId, String category, String address, String productName, Float starAvg,
record 사용해주셨네요! 저도 좀 자세히 공부해봐야겠어요 ㅎㅎ

2023-11-23 15:50 UTC, JeongUijeong commented on src/main/java/com/fc/shimpyo_be/domain/product/service/ProductService.java
> +    public List<ProductResponse> getAllProducts(final String productName, final String address,
별건 아니지만, getAllProducts를 getProducts라고 하셔도 복수이기 때문에 상품 리스트를 가져온다는 의미를 충분히 담을 수 있지 않을까요?

2023-11-23 15:50 UTC, JeongUijeong commented on src/main/java/com/fc/shimpyo_be/domain/product/service/ProductService.java
> +            throw new ProductNotFoundException();
조회 결과가 없는 게 예외일까요?? 검색 결과 일치하는 상품이 없는 경우 예외 처리보단 빈 리스트를 반환하는 것이 좋을 것 같습니다!

2023-11-23 15:50 UTC, JeongUijeong commented on src/main/java/com/fc/shimpyo_be/domain/product/util/CategoryConverter.java
혹시 이건 어디서 어떻게 쓰이는 건지 설명해주실 수 있을까요??

2023-11-23 15:50 UTC, JeongUijeong commented on src/main/java/com/fc/shimpyo_be/domain/product/util/ImageUrlParser.java
> +        return Arrays.stream(imageUrl.split(",")).toList();
Url 여러개를 ","로 구분해서 사용하시는 것 같은데 productImage 테이블을 사용하도록 수정하셔야 합니다..! ERD 참고해주세요!

2023-11-23 15:50 UTC, JeongUijeong commented on src/main/java/com/fc/shimpyo_be/domain/room/dto/response/RoomResponse.java
> +@Builder
빌더를 생성자에 붙이시면 좀 더 안정적입니다!

2023-11-23 15:50 UTC, JeongUijeong commented on src/main/java/com/fc/shimpyo_be/global/exception/ErrorCode.java
ErrorCode enum 만들어주셔서 감사합니다! 저도 얼른 적용하도록 하겠습니다! ㅎㅎ

2023-11-23 15:50 UTC, JeongUijeong commented on src/main/java/com/fc/shimpyo_be/domain/product/controller/ProductRestController.java
> +        @RequestParam(required = false) String category,
requestParam으로 받은 값들을 Dto에 담아서 사용하는 것은 어떨까요?

2023-11-23 16:28 UTC, wocjf0513 commented on src/main/java/com/fc/shimpyo_be/domain/product/controller/ProductRestController.java
> +    @GetMapping("")
몰랐습니다. 감사합니다!

2023-11-23 16:30 UTC, wocjf0513 commented on src/main/java/com/fc/shimpyo_be/domain/product/controller/ProductRestController.java
> +    public ResponseDto<List<ProductResponse>> getAllProducts(
ResponseDto를 처음 써봐서. ResposeEntity안에 넣는지 몰랐네요. 수정하겠습니다!

2023-11-23 16:32 UTC, wocjf0513 commented on src/main/java/com/fc/shimpyo_be/domain/product/dto/response/ProductDetailsResponse.java
> +                                     String productName, String description, Boolean favorites, Float starAvg,
ctrl + shift + L 해서 적용하는데 이 부분 적용이 안된거 같네요. 배워가겠습니다

2023-11-23 16:35 UTC, wocjf0513 commented on src/main/java/com/fc/shimpyo_be/domain/product/service/ProductService.java
> +    public List<ProductResponse> getAllProducts(final String productName, final String address,
ALL 이랑 Products가 중복돼서 좀 그렇긴 하네요. 그래도 전체 상품을 가져온다는 의미에서 ALL을 쓰고 싶긴한데, 어떻게 해야 될지 고민이 필요할거같습니다.

2023-11-23 16:35 UTC, wocjf0513 commented on src/main/java/com/fc/shimpyo_be/domain/product/service/ProductService.java
> +            throw new ProductNotFoundException();
빈 리스트를 보낼지 ,exception을 보낼지 고민했는데 적용하겠습니다.

2023-11-23 16:41 UTC, wocjf0513 commented on src/main/java/com/fc/shimpyo_be/domain/product/util/CategoryConverter.java
@Enumerated(EnumType.STRING) 쓰다가 jpa spection 사용하는 부분에서 오류가 나서, converter 사용하게 된거 같습니다.
enum타입을 어떻게 db에 저장할건지, db에 있는 string을 어떻게 enum으로 가져올건지 사용했습니다.

2023-11-23 16:41 UTC, wocjf0513 commented on src/main/java/com/fc/shimpyo_be/domain/product/util/ImageUrlParser.java
> +        return Arrays.stream(imageUrl.split(",")).toList();
초반에 erd에 productImage가 없었다가 나중에 추가되서 중간 배포까지는 이렇게 쓰다가 중간 배포 끝나면 erd대로 만들 거 같습니다.

2023-11-23 16:42 UTC, wocjf0513 commented on src/main/java/com/fc/shimpyo_be/domain/room/dto/response/RoomResponse.java
> +@Builder
이유를 잘 몰라서 왜 그런지 알 수 있을까요?

2023-11-23 16:43 UTC, wocjf0513 commented on src/main/java/com/fc/shimpyo_be/global/exception/ErrorCode.java
감사합니다~!

2023-11-23 16:45 UTC, wocjf0513 commented on src/main/java/com/fc/shimpyo_be/domain/product/controller/ProductRestController.java
> +        @RequestParam(required = false) String category,
생각을 했었는데 찾고자 하니까 안 나와서 
@RequestParam 객체 (객체변수명) 이렇게 사용할 수 있나요? 그러면 필드에 맵핑되는건가요?

2023-11-24 06:48 UTC, JeongUijeong commented on src/main/java/com/fc/shimpyo_be/domain/room/dto/response/RoomResponse.java
> +@Builder
https://jake-seo-dev.tistory.com/70 참고하시면 좋을 것 같아요!

2023-11-25 15:54 UTC, jo0oy approved these changes
수고하셨습니다~

2023-11-26 08:17 UTC, JeongUijeong approved these changes

2023-11-26 08:17 UTC, merged